### ISSUE TITLE
Conversion of get-config response to XML crashes on IOS-XE 16.11.1b

### ISSUE THREAD

**Issue by dmfigol** [scrapli/scrapli_netconf#1]
**Describe the bug**
When I retrieve get-config response from IOS-XE 16.11.1b the application crashes when trying to convert the result to XML

**To Reproduce**
1. Your script
```
CONN_DATA = {
    "host": "192.168.153.101",
    "auth_username": "cisco",
    "auth_password": "cisco",
    "auth_strict_key": False,
    "ssh_config_file": True,
    "transport": "system",
    "port": 830
}
conn = NetconfScrape(**CONN_DATA)
conn.open()
response = conn.get_config(source="running")
print(response.result)
```
2. What you're connecting to (vendor, platform, version): Cisco IOS-XE 16.11.1b

**Expected behavior**
Not crash

**Stack Trace**
```
Traceback (most recent call last):
  File "/home/dmfigol/.pyenv/versions/3.7.7/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/home/dmfigol/.pyenv/versions/3.7.7/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/dmfigol/.pyenv/versions/3.7.7/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/dmfigol/projects/network-programmability-stream/scrapli-apps/netconf.py", line 1, in <module>
    from scrapli_netconf.driver import NetconfScrape
  File "/home/dmfigol/projects/network-programmability-stream/scrapli-apps/.venv/lib/python3.7/site-packages/scrapli_netconf/driver/driver.py", line 248, in get_config
    response._record_response(raw_response)  # pylint: disable=W0212
  File "/home/dmfigol/projects/network-programmability-stream/scrapli-apps/.venv/lib/python3.7/site-packages/scrapli_netconf/response.py", line 76, in _record_response
    self._record_response_netconf_1_1()
  File "/home/dmfigol/projects/network-programmability-stream/scrapli-apps/.venv/lib/python3.7/site-packages/scrapli_netconf/response.py", line 133, in _record_response_netconf_1_1
    "\n".join([result[1].rstrip() for result in result_sections])
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**OS (please complete the following information):**
 - OS: Ubuntu
 - scrapli version: 2020.5.9
 - scrapli_netconf version: 2020.4.19

**Additional context**
[get-config-response.txt](https://github.com/scrapli/scrapli_netconf/files/4640944/get-config-response.txt)

The problem is that the response has XML encoding specified, but is already a decoded string. 
I suspect that the proper way to handle it is to use bytes everywhere.
https://stackoverflow.com/questions/28534460/lxml-etree-xml-valueerror-for-unicode-string
https://lxml.de/parsing.html
E.g. after I saved provided XML to a file, this works:
`etree.XML(Path("get-config-response.xml").read_bytes())`

**Comment by carlmontanari** [comment]
Hey @dmfigol 

Sorry for the big delay here.

I was able to re-create this issue as expected. This was occurring for exactly the reasons you outlined of course :) -- the recap: in the response object we craft an lxml Element from the string result we get back from the device. IOSXE devices always include the xml document header which includes encoding (this does not seem to be the case for iosxr/junos which is why I hadn't spotted this yet).

As you pointed out this is because we've already got a decoded string. It probably would be better to just have bytes everywhere, however we are already getting back a string from the underlying scrapli "core" bits that are reading the data off the socket/transport. So the somewhat not great fix is that prior to rebuilding the Element to add to the response object, I've added a string replace to strip the document header and replace it with nothing.

This is now in master and the fix has been tested against current always on sandbox and looks to be working nicely. I'd love to say that I've added tests to cover this but I haven't yet :) Hopefully will be getting some basic unit tests for this repo built up today... but we'll see! Anyway, going to close this out, please re-open if this is still an issue!

Carl
