### ISSUE TITLE
Type 'NoneType' cannot be serialized (lxml.etree.tostring)

### ISSUE THREAD

**Issue by lastorel** [scrapli/scrapli_netconf#127]
**Describe the bug**
My devices return unexpected symbol `\x07` with rpc-reply.
Like #1 
It returns data: `NetconfResponse.raw_result = b'\x07<rpc-reply xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="120">\n<ok/>\n</rpc-reply>\n]]>]]>\n'`
And `etree.fromstring` can not parse it at https://github.com/scrapli/scrapli_netconf/blob/2022.07.30/scrapli_netconf/response.py#L131

**To Reproduce**
1. Your script
Well, it's complicated. And it reproduces only when xml config string is long.  
But I was able to replicate this behavior like that:
```python
from scrapli_netconf import NetconfDriver
dev = NetconfDriver(
    host="10.10.10.10", port=22, auth_username="egor", auth_password="password", auth_strict_key=False, transport="ssh2"
)
# users and key information is fake
filter = """\
<config>
    <configuration>
        <system>
            <login>
                <retry-options operation="replace">
                    <tries-before-disconnect>5</tries-before-disconnect>
                    <backoff-threshold>2</backoff-threshold>
                    <backoff-factor>5</backoff-factor>
                    <minimum-time>30</minimum-time>
                    <lockout-period>15</lockout-period>
                </retry-options>
                <idle-timeout>60</idle-timeout>
                <class operation="replace">
                    <name>engineer</name>
                    <permissions>clear</permissions>
                    <permissions>configure</permissions>
                    <permissions>firewall-control</permissions>
                    <permissions>interface-control</permissions>
                    <permissions>network</permissions>
                    <permissions>reset</permissions>
                    <permissions>rollback</permissions>
                    <permissions>routing-control</permissions>
                    <permissions>view</permissions>
                    <permissions>view-configuration</permissions>
                </class>
                <class operation="replace">
                    <name>read-only-extended</name>
                    <permissions>view</permissions>
                    <permissions>view-configuration</permissions>
                </class>
                <user operation="remove">
                </user>
                <user>
                    <name>aaa</name>
                    <full-name>aaa</full-name>
                    <uid>2031</uid>
                    <class>super-user</class>
                    <authentication>
                        <encrypted-password>$6$f245f234v5g3456ybh6nj56nhtrhnrtnhrtyhn46yhn46ynytrbn56ynh56yhn456yhetrhnt4trg35n3tg3t5gdgdbn5hn</encrypted-password>
                    </authentication>
                </user>
                <user>
                    <name>bbb</name>
                    <uid>2013</uid>
                    <class>super-user</class>
                    <authentication>
                        <encrypted-password>$6$f245f234v5g3456ybh6nj56nhtrhnrtnhrtyhn46yhn46ynytrbn56ynh56yhn456yhetrhnt4trg35n3tg3t5gdgdbn5hn</encrypted-password>
                    </authentication>
                </user>
                <user>
                    <name>ccc</name>
                    <full-name>ccc</full-name>
                    <uid>2033</uid>
                    <class>super-user</class>
                    <authentication>
                        <encrypted-password>$6$f245f234v5g3456ybh6nj56nhtrhnrtnhrtyhn46yhn46ynytrbn56ynh56yhn456yhetrhnt4trg35n3tg3t5gdgdbn5hn</encrypted-password>
                    </authentication>
                </user>
                <user>
                    <name>ddd</name>
                    <full-name>ddd</full-name>
                    <uid>2032</uid>
                    <class>super-user</class>
                    <authentication>
                        <encrypted-password>$6$f245f234v5g3456ybh6nj56nhtrhnrtnhrtyhn46yhn46ynytrbn56ynh56yhn456yhetrhnt4trg35n3tg3t5gdgdbn5hn</encrypted-password>
                    </authentication>
                </user>
                <user>
                    <name>eee</name>
                    <uid>1991</uid>
                    <class>super-user</class>
                    <authentication>
                        <ssh-rsa>
                            <name>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1fLnWqZXhHtB9uY+Bcl0TocxbpJBwb6MOGS3RbqFELnD1e/Pub1+wZpmqsCTglZqH3kVTlxaNFaWUzSxGp6cMY8TRHqUOlQuHo1SohetkmF5X1vClLeaKRJLwz0oM7OUujgx5srWIixk3R9xaAprL9mCqIwoimQ6o+xrAQln0iNlg2o5ffJPGCgKo7KwHlSQshK6yASw5cuMQbrpCfynOMDTGQYdPZHZyr824ecadGSDngMXpPlVgZeWQ2oabhCO52NCu/YxhHAL+pYhSyfPpBIz5q9tkZbJalq6LSGklf3FRehoUFJm9XTUtBtfwouw9XxCl2DLoLaPUqu0/p8/3 ubuntu@ubuntu</name>
                        </ssh-rsa>
                    </authentication>
                </user>
                <message>;qejrgpqeoruighpqeoirghpqoiehfgnpqor reou hfwepou weprufhweprouf hweprgofuihw 3p2 hpr39fu h13rfo 1h3rpo 3hrf [103rh f2rfg 234tg 24t fe</message>
            </login>
            <services operation="replace">
                <ssh>
                    <root-login>deny</root-login>
                    <connection-limit>5</connection-limit>
                    <rate-limit>5</rate-limit>
                </ssh>
                <netconf>
                    <ssh>
                    </ssh>
                </netconf>
            </services>
            <authentication-order operation="remove">
            </authentication-order>
            <authentication-order>password</authentication-order>
            <tacplus-server operation="remove">
            </tacplus-server>
        </system>
    </configuration>
</config>
"""
dev.open()
r = dev.edit_config(config=filter, target="candidate")
dev.discard()
dev.close()
```
2. What you're connecting to (vendor, platform, version)
Juniper JunOS versions: 20.2R2.11 and 21.4R3-S2.3
3. Anything else relevant
My workaround is to add another `.replace()` to `self.xml_result = etree.fromstring(...`

**Expected behavior**
Not crash

**Stack Trace**
```
Traceback (most recent call last):
  File "C:\Users\GomzinED\Pycharm\network_bot\venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "C:\Users\GomzinED\Pycharm\network_bot\juniper\custom_netconf.py", line 42, in netconf_edit_config
    scrapli_response = scrapli_conn.edit_config(config=config, target=target)
  File "C:\Users\GomzinED\Pycharm\network_bot\venv\lib\site-packages\scrapli_netconf\driver\sync_driver.py", line 202, in edit_config
    response.record_response(raw_response)
  File "C:\Users\GomzinED\Pycharm\network_bot\venv\lib\site-packages\scrapli_netconf\response.py", line 112, in record_response
    self._record_response_netconf_1_0()
  File "C:\Users\GomzinED\Pycharm\network_bot\venv\lib\site-packages\scrapli_netconf\response.py", line 146, in _record_response_netconf_1_0
    self.result = etree.tostring(self.xml_result, pretty_print=True).decode()
  File "src\lxml\etree.pyx", line 3465, in lxml.etree.tostring
TypeError: Type 'NoneType' cannot be serialized.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/51007870/211605249-5bece727-4084-444e-93b1-2c8dc82c8402.png)

**OS (please complete the following information):**
 - OS: **Windows 10, Ubuntu 18.04.5**
 - scrapli version **2021.7.30**
 - scrapli_netconf version **2021.7.30**
 - ssh2-python version **1.0.0**

**Additional context**
It does not reproduces with `system` transport! With `ssh2` only.

**Comment by carlmontanari** [comment]
hey, thanks for opening this @lastorel -- hopefully will get some time to take a peak this weekend, just didn't wanna leave ya hangin in the meantime!

**Comment by carlmontanari** [comment]
interesting this is only with ssh2 transport! also interesting is that thats the "terminal bell" symbol. dunno why, just interesting 😁 unfortunately I couldn't reproduce on the Junos version I have handy (17.x) but I can see this obviously being an issue, so defo wanna get it sorted out (and ideally this week since next release is set for not too long from now).

I sorta worry about just tacking on a replace there in case other chars pop up. I also think this lib has been around a while and this is the first time I've seen this crop up, so I'm thinking the fix should be fairly non intrusive and only execute in case of failure to parse. maybe something like the following in the response 1_0 record, what do you think?

```python
    @classmethod
    def _parse_raw_result(cls, raw_result: bytes) -> bytes:
        # remove the message end characters and xml document header see:
        # https://github.com/scrapli/scrapli_netconf/issues/1
        _raw_result = raw_result.replace(b"]]>]]>", b"").replace(
            b'<?xml version="1.0" encoding="UTF-8"?>', b""
        )

        parsed_result = etree.fromstring(
            _raw_result,
            parser=PARSER,
        )

        if parsed_result is None:
            parsed_result = etree.fromstring(
                CONTROL_CHARS.sub(b"", _raw_result),
                parser=PARSER,
            )

        return parsed_result

    def _record_response_netconf_1_0(self) -> None:
        """
        Record response for netconf version 1.0

        Args:
            N/A

        Returns:
            N/A  # noqa: DAR202

        Raises:
            N/A

        """
        self.xml_result = self._parse_raw_result(self.raw_result)

        if self.strip_namespaces:
            self.xml_result = remove_namespaces(self.xml_result)
            self.result = etree.tostring(self.xml_result, pretty_print=True).decode()
        else:
            self.result = etree.tostring(self.xml_result, pretty_print=True).decode()
```

with a new compiled pattern outside the class like:

```python
# CONTROL_CHARS matches control chars we do not want to see in text output, such as \x07 (terminal
# bell). See #127 for more details.
CONTROL_CHARS = re.compile(rb"[\x00-\x1f\x7f-\x9f]")
```

I feel like this would sort this problem out and also not really change much/not add overhead unless it is needed.

thoughts?

thanks for raising this and the info!

carl

**Comment by carlmontanari** [comment]
Cool, thanks for the help here @lastorel -- just pushed to main with that fix so will be in the next release!

carl
