### ISSUE TITLE
Error: lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !

### ISSUE THREAD

**Issue by BluSpanner** [scrapli/scrapli_netconf#140]
**Describe the bug**
```
Getting the following error, when attempting to dump config on 1 out of 40 devices.
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xCD 0xCD 0xCD 0xCD, line 693552, column 14
```

**To Reproduce**
1. Your script

```
import sys
from scrapli_netconf.driver import NetconfDriver
from settings import HOST
from settings import USERNAME
from settings import PASSWORD

device = {
    "host": HOST,
    "port": 22,
    "auth_username": USERNAME,
    "auth_password": PASSWORD,
    "strip_namespaces": True,
    "transport": "paramiko",
    'timeout_socket': 180,
    'timeout_transport': 180,
    'timeout_ops': 180,
}

connection = NetconfDriver(**device)
connection.open()
config = connection.get_config(source="running")

```
2. What you're connecting to (vendor, platform, version)
`Cisco ASR 9903 Router`

**Stack Trace**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.11/site-packages/scrapli_netconf/driver/sync_driver.py", line 177, in get_config
response.record_response(raw_response)
  File ".../lib/python3.11/site-packages/scrapli_netconf/response.py", line 114, in record_response
    self._record_response_netconf_1_1()
  File ".../ccd/lib/python3.11/site-packages/scrapli_netconf/response.py", line 267, in _record_response_netconf_1_1
    self.xml_result = etree.fromstring(
                      ^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3257, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1803, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1144, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError
  File "<string>", line 693552
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xCD 0xCD 0xCD 0xCD, line 693552, column 14
```

**OS (please complete the following information):**
 - OS: [e.g. Ubuntu, MacOS, etc. - Note scrapli_netconf is *not* supported on Windows]
 ```
OS: Ubuntu
paramiko           3.3.1
scrapli            2023.7.30
scrapli-netconf    2023.7.30
```

**Comment by carlmontanari** [comment]
👋 thats an exception coming from lxml -- there was an older similar (I think) issue in #18 -- but iirc adding `recover=true` in the xml parser solved this. do you have some special characters or something in a description or anywhere else in the config/whatever you are fetching? can you get the raw xml and share that and/or try to parse it w/ lxml?

**Comment by BluSpanner** [comment]
Thanks for the reply...
Running with debug, the `scrapli.log` file doesn't contain any 0xCD characters.
As I'm not calling lxml directly.  Where does `recover=true`, get added?

**Comment by carlmontanari** [comment]
you won't see 0xCD - I think its a `Í` character. that in your config somewhere? recover is already set [here](https://github.com/scrapli/scrapli_netconf/blob/main/scrapli_netconf/response.py#L25). basically you have bad utf-8 and lxml barfs is all I know :D. if you share the config/section with it if you can narrow it down I can look more.

**Comment by BluSpanner** [comment]
I don't see any `0xCD` characters in the `scrapli.log` file.
Here's the script I used to check...
```
import collections
INFILE = 'scrapli.log'
count = collections.Counter()
file = open('scrapli.log', "r", encoding="utf8")
for line in file.readlines():
    for c in line:
        count[ord(c)] += 1

for character in sorted(list(count)):
    print(chr(character), hex(character), count[character])

```
And the output...

```
 0xa 31
  0x20 4722323
" 0x22 67358
# 0x23 84
$ 0x24 21
% 0x25 18
& 0x26 3517
' 0x27 2264
( 0x28 1
) 0x29 1
* 0x2a 725
, 0x2c 1987
- 0x2d 1142489
. 0x2e 54998
/ 0x2f 637537
0 0x30 195958
1 0x31 157047
2 0x32 162970
3 0x33 91363
4 0x34 72590
5 0x35 50253
6 0x36 68506
7 0x37 46161
8 0x38 41468
9 0x39 50723
: 0x3a 51588
; 0x3b 2356
< 0x3c 911621
= 0x3d 40456
> 0x3e 911625
? 0x3f 3292
A 0x41 60186
B 0x42 61988
C 0x43 48109
D 0x44 6171
E 0x45 31103
F 0x46 5754
G 0x47 4540
H 0x48 6851
I 0x49 42568
J 0x4a 16
K 0x4b 5033
L 0x4c 51689
M 0x4d 13342
N 0x4e 15940
O 0x4f 70771
P 0x50 30980
Q 0x51 70
R 0x52 48437
S 0x53 77022
T 0x54 69314
U 0x55 5068
V 0x56 2885
W 0x57 8296
X 0x58 37344
Y 0x59 4012
Z 0x5a 2065
[ 0x5b 2
\ 0x5c 696829
] 0x5d 10
_ 0x5f 105856
a 0x61 905516
b 0x62 259167
c 0x63 641554
d 0x64 438664
e 0x65 1278656
f 0x66 163565
g 0x67 405619
h 0x68 134243
i 0x69 1006020
j 0x6a 65
k 0x6b 8465
l 0x6c 307484
m 0x6d 391167
n 0x6e 1798103
o 0x6f 686758
p 0x70 460465
q 0x71 44812
r 0x72 713269
s 0x73 681472
t 0x74 1096392
u 0x75 277475
v 0x76 266947
w 0x77 98141
x 0x78 91233
y 0x79 209217
z 0x7a 73
| 0x7c 100
```

**Comment by carlmontanari** [comment]
you're going to be much better off just dumping a breakpoint in the response somewhere around [here](https://github.com/scrapli/scrapli_netconf/blob/main/scrapli_netconf/response.py#L266). 

I cant really do much other than say that the char is in there somewhere and lxml doesnt like it. I dunno if the writer object just handles/normalizes the char and thats why it's not in the log or something like that (an interesting side quest perhaps). if you breakpoint there and snag the output and share that I think that will be much more useful since its right before the issue occurs and should be fairly clear whats up (and maybe/hopefully easy to fix? but no promises, esp as lxml is the one complaining not scrapli)

**Comment by carlmontanari** [comment]
gunna close this for now. holler if ya can get us some more info and we can figure out what's what!
